# Generated by Django 5.0 on 2024-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=50),
        ),
    ]
